### ISSUE TITLE
Remote MotionEye cameras always use root host URL in `get_camera_stream_url`

### ISSUE THREAD

**Issue by DarkC35** [dermotduffy/motioneye-client#141]
## Version

0.3.12

## Describe the bug

Hi I just found a bug while using this library in the official HA integration and I think I can propose a rather easy solution:

I have 4 Raspis running MotionEyeOS and finally added them yesterday to HA. One of those 4 (let's call it `m-1`) is configured to show all 4 cameras, so `m-2`, `m-3`, and `m-4` are added as `Remote motionEye camera` on `m-1`. Since I started with `m-1` to add them to HA I got the success message that all 4 cameras were created and I was able to use them everywhere (as a `picture-entity` in the dashboard, I saw all of them in the `media` sections `Camera` and `motionEye Media` and so on). Everything seems to work until I clicked on one of the remote cameras to open the `more-info` dialog to get a larger picture of the camera stream. On the `more-info` dialog it always shows the stream of `m-1` on all 4 camera entities (the preview uses the `camera_proxy` api, the `more-info` dialog the `camera_proxy_stream` api). After messing with the HA core codebase I looked into this lib and I think I found out what causes this behaviour: 

The `get_camera_stream_url` function always uses the root host here instead of the remote host URL when a remote camera is used:
https://github.com/dermotduffy/motioneye-client/blob/aa86788f3e2844e815e7cc1a04ba443f3550c889/motioneye_client/client.py#L242

When you call `await client.async_get_cameras()` on a motionEye host that has `remote motioneye cameras` configured you can see that all remote cameras provide a `host` property in the dictionary with the right URL (the root camera does not provide this key).

My proposed solution would look like this:
```py
host = camera.get("host", urlsplit(self._url).netloc.split(":")[0])
```
This way it should use the `host` property from the config if provided and only fallback to the root host when there is no `host` property (as it is for the root camera).

## Debug log

No relevant logs as no errors/warnings occure.

```text

2023-01-07 13:11:48.468 DEBUG (MainThread) [homeassistant.components.motioneye] Finished fetching motioneye data in 0.303 seconds (success: True)

```

**Comment by dermotduffy** [comment]
Thanks @DarkC35 . I don't have a remote motionEye camera setup (and so didn't test with one), so not surprised there are wrinkles here. Can you share an example dictionary with the `host` property you're talking about? I'd like to add a unittest...

**Comment by DarkC35** [comment]
Sure, thanks for taking on this issue since I was not sure how you want to unit test this!

Here is the dict (I renamed the cameras to `m-1` and `m-2` and redacted properties like `webhook_urls` and `passwords` manually). (GH does not allow `.py` files therefore I zipped it.)
[cameras-dict.zip](https://github.com/dermotduffy/motioneye-client/files/10367282/cameras-dict.zip)

You can easily test this yourself by visiting the motionEye UI of one of your cameras and add it as a remote camera to itself (yeah it sounds stupid but it actually works to get the dict, you cannot reproduce the HA bug though): Login -> Click on the camera name in the top left corner -> choose `add camera...` -> select `Remote motionEye camera` -> provide the login data -> hit add -> call `await client.async_get_cameras()`

I already replaced your original line with my proposed one and it worked as expected in my dev environment (`camera_proxy_stream` now points to the right host in HA).

**Comment by dermotduffy** [comment]
@DarkC35 Thank you! Leave it with me.

**Comment by DarkC35** [comment]
Thank you so much @dermotduffy! You are saving me from manually disabling all remote ones and adding them individually to HA. I was afraid that this workaround could mess up the webhook logic.
