### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by DARKFiB3R** [dermotduffy/motioneye-client#64]
Hi there, I hope this is the correct place to report an issue I'm having.

Trying to use motionEye for the first time, but when trying to configure the integration with usernames and passwords, I'm getting the error "Invalid authentication".

**Comment by dermotduffy** [comment]
Hi @DARKFiB3R , are you referring to Home Assistant? This repo is for the underlying client library, rather than HA itself, so bugs should probably be filed over there. Did you figure it out?
